<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>FastHelmetCustom</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.Common">
      <HintPath>..\..\SPT\SPTarkov.Common.dll</HintPath>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>..\..\SPT\SPTarkov.DI.dll</HintPath>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>..\..\SPT\SPTarkov.Server.Core.dll</HintPath>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>..\..\SPT\SemanticVersioning.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
